### ISSUE TITLE
Системная кнопка назад срабатывает не с первого раза

### ISSUE THREAD

**Issue by reyzitwo** [alexz9/react-router-vkminiapps#4]

**Comment by alexz9** [comment]
Метод bridge VKWebAppSetLocation берет на себя лишний step. 
Повлиять на это со своей стороны возможности нет.

Проявляется только с ПК при использовании хеш-навигации. С телефона, где в основном и используется системная кнопка, всё ок.

**Comment by reyzitwo** [comment]
Наоборот, у меня это актуально на двух платформах: web & android

**Comment by alexz9** [comment]
Возможно вызываете метод несколько раз или создаете дубль истории у себя. В наших проектах всё ок. Библиотека написана для себя. Никто из нас не будет решать ваши проблемы.

**Comment by reyzitwo** [comment]
> Библиотека написана для себя. Никто из нас не будет решать ваши проблемы.

Зачем тогда выкладывать проект на гитхаб, так ещё как и открытый репозиторий?

**Comment by alexz9** [comment]
Молодой человек, вы по моему что-то попутали. По вашему я должен за вас решать ваши проблемы и фиксить ваши баги только потому, что я сделал для себя библиотеку и не закрыл её от других пользователей? Вы в своей уме? Вам сколько лет?

**Comment by reyzitwo** [comment]
Вы не должны за меня решать "мои" проблемы. Я нашел баги и сообщил об этом разработчику, кажется, так и должно же работать? Ведь если проблемы существует, значит они не замечена вами, а я хотел только помочь вам - сделать продукт лучше.

Не беспокойтесь, я пофиксил это со своей стороны. Даже если все _нормально_ функционирует с вашей стороны, это не значит, что проблем не существует, на них можно закрыть глаза, и все будет хорошо :)

**Comment by reyzitwo** [comment]
Если вы не принимаете ишью, то могли бы просто их выключить.
Settings -> Features -> Issues
![image](https://user-images.githubusercontent.com/73870113/146648055-28f1834d-908d-4938-877d-e1afae195e30.png)
